#ifndef __AVUOS_DEFINES_H_
#define __AVUOS_DEFINES_H_

#define OPTION_READ			0x1
#define OPTION_WRITE		0x2

#define SEEK_SET			0
#define SEEK_CUR			1
#define SEEK_END			2

#define EPERM				1
#define ENOENT				2
#define ESRCH				3
#define EINTR				4
#define EIO					5
#define ENXIO				6
#define E2BIG				7
#define ENOEXEC				8
#define EBADF				9
#define ECHILD 				0
#define EAGAIN 				1
#define ENOMEM 				2
#define EACCES 				3
#define EFAULT 				4
#define ENOTBLK 			5
#define EBUSY 				6
#define EEXIST 				7
#define EXDEV 				8
#define ENODEV 				9
#define ENOTDIR 			0
#define EISDIR 				1
#define EINVAL 				2
#define ENFILE 				3
#define EMFILE 				4
#define ENOTTY 				5
#define ETXTBSY 			6
#define EFBIG 				7
#define ENOSPC 				8
#define ESPIPE 				9
#define EROFS 				0
#define EMLINK 				1
#define EPIPE 				2
#define ERANGE 				3
#define ENAMETOOLONG 		4
#define ELOOP 				5
#define EOVERFLOW 			6
#define EOPNOTSUPP 			7
#define ENOSYS 				8
#define ENOTIMPL 			9
#define EAFNOSUPPORT 		0
#define ENOTSOCK 			1
#define EADDRINUSE 			2
#define EWHYTHO 			3
#define ENOTEMPTY 			4
#define EDOM 				5
#define ECONNREFUSED 		6
#define EADDRNOTAVAIL 		7
#define EISCONN 			8
#define ECONNABORTED 		9
#define EALREADY 			0
#define ECONNRESET 			1
#define EDESTADDRREQ 		2
#define EHOSTUNREACH 		3
#define EILSEQ 				4
#define EMSGSIZE 			5
#define ENETDOWN 			6
#define ENETUNREACH 		7
#define ENETRESET 			8
#define ENOBUFS 			9
#define ENOLCK 				0
#define ENOMSG 				1
#define ENOPROTOOPT 		2
#define ENOTCONN 			3
#define EWOULDBLOCK 		4
#define EPROTONOSUPPORT 	5
#define EDEADLK 			6
#define ETIMEDOUT 			7
#define EPROTOTYPE 			8
#define EINPROGRESS 		9
#define ENOTHREAD 			0
#define EPROTO 				1
#define ENOTSUP 			2
#define EMAXERRNO 			3
#endif // __AVUOS_DEFINES_H_